### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'

### ISSUE THREAD

**Issue by Bestporter** [Python3WebSpider/DeepLearningImageCaptcha#1]
在执行步骤三：
```bash
    python train.py
```
出现下面的错误
```python
epoch: 0 step: 0 loss: 0.7400339245796204
Traceback (most recent call last):
  File "L:\Projects\chapter8\DeepLearningImageCaptcha\train.py", line 49, in <module>
    main()
  File "L:\Projects\chapter8\DeepLearningImageCaptcha\train.py", line 39, in main
    eval_acc = evaluate()
  File "L:\Projects\chapter8\DeepLearningImageCaptcha\evaluate.py", line 14, in main
    cnn.load_state_dict(torch.load('model.pkl'))
  File "L:\Projects\calculate\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "L:\Projects\calculate\lib\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "L:\Projects\calculate\lib\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
```
在项目根目录下，手动创建文件model.pkl之后，再次运行步骤三的命令，出现下面的错误
```python
epoch: 0 step: 0 loss: 0.7259010672569275
Traceback (most recent call last):
  File "L:\Projects\chapter8\DeepLearningImageCaptcha\train.py", line 49, in <module>
    main()
  File "L:\Projects\chapter8\DeepLearningImageCaptcha\train.py", line 39, in main
    eval_acc = evaluate()
  File "L:\Projects\chapter8\DeepLearningImageCaptcha\evaluate.py", line 14, in main
    cnn.load_state_dict(torch.load('model.pkl'))
  File "L:\Projects\calculate\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "L:\Projects\calculate\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
```
求大佬帮忙。

**Comment by Bestporter** [comment]
Python 3.10.2，torch==1.11.0，torchvision==0.12.0

**Comment by Bestporter** [comment]
照着书上先生成训练数据，然后生成验证数据，来回弄了两次后，莫名其妙可以运行了。

**Comment by conanyangqun** [comment]
> 照着书上先生成训练数据，然后生成验证数据，来回弄了两次后，莫名其妙可以运行了。

训练前，需要生成足够数量的训练数据和验证数据，即train和eval。看train.py中的代码，似乎至少要640张以上。所以按照书上的10万张训练应该没问题。

**Comment by Niklalala** [comment]
书中推荐的 ‘’使用GPU来训练模型，速度会比不用GPU快很多’‘，请问哈你们有设置成功的吗，在网上找了很多设置GPU来训练模型的方法，但始终设置不成功

**Comment by Niklalala** [comment]
> 书中推荐的 ‘’使用GPU来训练模型，速度会比不用GPU快很多’‘，请问哈你们有设置成功的吗，在网上找了很多设置GPU来训练模型的方法，但始终设置不成功

默认使用的'‘CPU在训练模型’，速度实在是太慢了

**Comment by Bestporter** [comment]
> > 书中推荐的 ‘’使用GPU来训练模型，速度会比不用GPU快很多’‘，请问哈你们有设置成功的吗，在网上找了很多设置GPU来训练模型的方法，但始终设置不成功
> 
> 默认使用的'‘CPU在训练模型’，速度实在是太慢了

我当时看的这个[博客](https://blog.csdn.net/weixin_43826681/article/details/109776079)，你可以看下，希望对你有帮助。

**Comment by Niklalala** [comment]
> > > 书中推荐的 ‘’使用GPU来训练模型，速度会比不用GPU快很多’‘，请问哈你们有设置成功的吗，在网上找了很多设置GPU来训练模型的方法，但始终设置不成功
> > 
> > 
> > 默认使用的'‘CPU在训练模型’，速度实在是太慢了
> 
> 我当时看的这个[博客](https://blog.csdn.net/weixin_43826681/article/details/109776079)，你可以看下，希望对你有帮助。

非常感谢，可以使用GPU训练模型了

**Comment by fateofdate** [comment]
你好 请问下pkl问题解决了吗？

**Comment by Niklalala** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by MR-Hgithub** [comment]
> 在执行步骤三：
> 
> ```shell
>     python train.py
> ```
> 
> 出现下面的错误
> 
> ```python
> epoch: 0 step: 0 loss: 0.7400339245796204
> Traceback (most recent call last):
>   File "L:\Projects\chapter8\DeepLearningImageCaptcha\train.py", line 49, in <module>
>     main()
>   File "L:\Projects\chapter8\DeepLearningImageCaptcha\train.py", line 39, in main
>     eval_acc = evaluate()
>   File "L:\Projects\chapter8\DeepLearningImageCaptcha\evaluate.py", line 14, in main
>     cnn.load_state_dict(torch.load('model.pkl'))
>   File "L:\Projects\calculate\lib\site-packages\torch\serialization.py", line 699, in load
>     with _open_file_like(f, 'rb') as opened_file:
>   File "L:\Projects\calculate\lib\site-packages\torch\serialization.py", line 231, in _open_file_like
>     return _open_file(name_or_buffer, mode)
>   File "L:\Projects\calculate\lib\site-packages\torch\serialization.py", line 212, in __init__
>     super(_open_file, self).__init__(open(name, mode))
> FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
> ```
> 
> 在项目根目录下，手动创建文件model.pkl之后，再次运行步骤三的命令，出现下面的错误
> 
> ```python
> epoch: 0 step: 0 loss: 0.7259010672569275
> Traceback (most recent call last):
>   File "L:\Projects\chapter8\DeepLearningImageCaptcha\train.py", line 49, in <module>
>     main()
>   File "L:\Projects\chapter8\DeepLearningImageCaptcha\train.py", line 39, in main
>     eval_acc = evaluate()
>   File "L:\Projects\chapter8\DeepLearningImageCaptcha\evaluate.py", line 14, in main
>     cnn.load_state_dict(torch.load('model.pkl'))
>   File "L:\Projects\calculate\lib\site-packages\torch\serialization.py", line 713, in load
>     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>   File "L:\Projects\calculate\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
>     magic_number = pickle_module.load(f, **pickle_load_args)
> EOFError: Ran out of input
> ```
> 
> 求大佬帮忙。

可以尝试将setting文件中将路径代码设置为“
EVAL_DATASET_PATH = 'dataset' + os.path.sep + 'eval'
TRAIN_DATASET_PATH = 'dataset' + os.path.sep + 'train'
”

**Comment by Niklalala** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
